### ISSUE TITLE
Unwanted message in signup page

### ISSUE THREAD

**Issue by Adarsh-Ghimire** [suyogya10/Tax-Calculator-System#27]
![image](https://user-images.githubusercontent.com/102452420/168586089-744daec5-7329-4708-83bd-803086890393.png)

**Comment by Adarsh-Ghimire** [comment]
please solve this @suyogya10

**Comment by suyogya10** [comment]
![image](https://user-images.githubusercontent.com/100501576/168587647-d661dd84-71b0-48c4-8531-f7951adb4472.png)
SOLVED
