### ISSUE TITLE
Drop down of news section is not workin

### ISSUE THREAD

**Issue by Adarsh-Ghimire** [suyogya10/Tax-Calculator-System#29]
![image](https://user-images.githubusercontent.com/102452420/168589327-83ddda9f-6378-4744-8841-4a9d1b2224a9.png)

**Comment by suyogya10** [comment]
![image](https://user-images.githubusercontent.com/100501576/168591176-58732960-7cfd-4c74-bc0e-698369baf1c1.png)

SOLVED
